In [1]:
import numpy as np
import pandas as pd

In [7]:
arr2d = np.random.randint(low=1,high=101, size=(5,5))
print(f"max w kazdej kolumnie: {np.max(arr2d, axis=0)}")
print(f"min w kazdym wierszu: {np.min(arr2d, axis=1)}")

max w kazdej kolumnie: [83 82 42 96 41]
min w kazdym wierszu: [16  6 18 26 11]


In [14]:
mean_arr2d = np.mean(arr2d)
std_arr2d = np.std(arr2d)

standarized_arr2d = (arr2d - mean_arr2d) / std_arr2d
print(standarized_arr2d)

[[ 1.30115078 -1.00880841 -0.47865384  0.50591893 -1.12241296]
 [ 1.41475534 -1.50109479 -0.13784019  1.90704172 -0.17570837]
 [-0.74373112  1.14967805 -0.21357655  0.16510528 -1.04667659]
 [ 0.77099622  0.08936891 -0.74373112  0.3544462  -0.63012657]
 [-1.19814933  1.37688715 -1.31175388  1.64196444 -0.36504929]]


In [12]:
#przekatna tablicy
przekatna = np.diag(arr2d)
sum_of_diagonal = np.sum(przekatna)
print(sum_of_diagonal)

217


In [26]:
tab = np.array([0,1])
rzuty = np.random.choice(tab, 1000)
procent_1 = round(len(rzuty[rzuty == 1]) / len(rzuty),4)
print(procent_1)

0.492


In [29]:
tab_1kk = np.random.randint(low=1, high=1000, size=(1000000))
print(f"avg value: {np.mean(tab_1kk)}")
print(f"Liczba unikalnych wartosci: {len(np.unique(tab_1kk))}")

avg value: 499.688845
Liczba unikalnych wartosci: 999


In [36]:
t = np.random.rand(50)
a = 0.5
index = (np.abs(t - a).argmin())
print(f"najblizsza wartosc:ma index {index} i wartosc: {t[index]}")

najblizsza wartosc:ma index 3 i wartosc: 0.49362304649199595
