In [12]:
import pandas as pd
import numpy as np

In [7]:
data= {"A": [11,12,13], "B": [33,44,55]}
df = pd.DataFrame(data)
df  

A   B
0  11  33
1  12  44
2  13  55

In [11]:
df.iloc[1:]

A   B
1  12  44
2  13  55

In [15]:
s = pd.Series(np.arange(3.))
s

0    0.0
1    1.0
2    2.0
dtype: float64

In [16]:
s[1]

1.0

In [18]:
s = pd.Series(np.arange(3.), index=['a','b','c'])
s["b"]

1.0

In [21]:
s.loc["b"]

1.0

In [24]:
df.loc[:, "B"] = 5
df

A  B
0  11  5
1  12  5
2  13  5

In [25]:
df.iloc[2] = 2
df

A  B
0  11  5
1  12  5
2   2  2

In [26]:
df.loc[df["A"] > 10]

A  B
0  11  5
1  12  5

In [27]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','b','c','d'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a','c','e','f','g'])

In [28]:
s1

a    7.3
b   -2.5
c    3.4
d    1.5
dtype: float64

In [29]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [30]:
s1 + s2

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [32]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [33]:
arr[0]

array([0., 1., 2., 3.])

In [34]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [35]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'), index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah    0.442890  2.083855  0.109006
Ohio   -0.383546  0.401980 -0.424515
Texas   0.712642  0.072357 -0.078747
Oregon  1.411535 -1.083964  0.789770

In [36]:
np.abs(frame)

b         d         e
Utah    0.442890  2.083855  0.109006
Ohio    0.383546  0.401980  0.424515
Texas   0.712642  0.072357  0.078747
Oregon  1.411535  1.083964  0.789770

In [40]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1, axis=1)

Utah      1.974849
Ohio      0.826496
Texas     0.791390
Oregon    2.495500
dtype: float64

In [43]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

frame.apply(f2)

b         d         e
min -0.383546 -1.083964 -0.424515
max  1.411535  2.083855  0.789770

In [45]:
def my_format(x):
    return f"{x:.2f}"

frame.map(my_format)

b      d      e
Utah     0.44   2.08   0.11
Ohio    -0.38   0.40  -0.42
Texas    0.71   0.07  -0.08
Oregon   1.41  -1.08   0.79

In [46]:
frame["e"].map(my_format)

Utah       0.11
Ohio      -0.42
Texas     -0.08
Oregon     0.79
Name: e, dtype: object

In [49]:

obj = pd.Series(np.arange(4), index=['d','a','c','b'])
obj

d    0
a    1
c    2
b    3
dtype: int32

In [50]:
obj.sort_index()

a    1
b    3
c    2
d    0
dtype: int32

In [51]:
obj.rank()

d    1.0
a    2.0
c    3.0
b    4.0
dtype: float64