In [1]:
import torch

In [2]:
torch.tensor(9)

tensor(9)

In [3]:
revenue = torch.tensor([100,120,90,75])
revenue

tensor([100, 120,  90,  75])

In [4]:
revenue[1:4]

tensor([120,  90,  75])

In [5]:
q1 = torch.tensor([
    [200,220,250],
    [150,180,210],
    [300,330,360]
])

q2 = torch.tensor([
    [209,231,259],
    [155,192,222],
    [310,340,375]
])

In [6]:
q1 + q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [7]:
q2 - q1

tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [8]:
q1 @ q2

tensor([[153400, 173440, 194390],
        [124350, 140610, 157560],
        [225450, 255060, 285960]])

In [9]:
q1 * q2

tensor([[ 41800,  50820,  64750],
        [ 23250,  34560,  46620],
        [ 93000, 112200, 135000]])

In [10]:
(q2-q1) * 100 / q1

tensor([[4.5000, 5.0000, 3.6000],
        [3.3333, 6.6667, 5.7143],
        [3.3333, 3.0303, 4.1667]])

In [11]:
return_rate = 0.1
q1 * return_rate , q2 * return_rate

(tensor([[20., 22., 25.],
         [15., 18., 21.],
         [30., 33., 36.]]),
 tensor([[20.9000, 23.1000, 25.9000],
         [15.5000, 19.2000, 22.2000],
         [31.0000, 34.0000, 37.5000]]))

In [12]:
profit_per_unit = torch.tensor([
    [30,27,25],
    [20,18,17],
    [45,38,39]
])

In [13]:
q1 * profit_per_unit

tensor([[ 6000,  5940,  6250],
        [ 3000,  3240,  3570],
        [13500, 12540, 14040]])

In [14]:
product_prices = torch.tensor([[1100,450,1500]])
product_prices

tensor([[1100,  450, 1500]])

In [15]:
product_prices @ q1

tensor([[737500, 818000, 909500]])

In [16]:
torch.matmul(product_prices,q1)

tensor([[737500, 818000, 909500]])

In [17]:
product_prices.t()

tensor([[1100],
        [ 450],
        [1500]])

In [18]:
q1

tensor([[200, 220, 250],
        [150, 180, 210],
        [300, 330, 360]])

In [19]:
prices_by_region = q1 * product_prices.t()
prices_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [20]:
prices_by_region.sum()

tensor(2465000)

In [21]:
prices_by_region.sum(dim=0)

tensor([737500, 818000, 909500])

In [22]:
usd_to_r = 83
prices_by_region * usd_to_r

tensor([[18260000, 20086000, 22825000],
        [ 5602500,  6723000,  7843500],
        [37350000, 41085000, 44820000]])

In [23]:
p_inr = (prices_by_region * usd_to_r).sum(dim=0)
p_inr

tensor([61212500, 67894000, 75488500])

In [24]:
torch.cuda.is_available()

True

In [25]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

In [26]:
import sys, torch, platform, os
print("Python:", sys.executable)
print("Torch:", torch.__version__)
print("Torch CUDA build:", torch.version.cuda)     # None => CPU-only wheel
print("CUDA available:", torch.cuda.is_available())
print("Devices:", torch.cuda.device_count())


Python: c:\Users\USER\AppData\Local\Programs\Python\Python311\python.exe
Torch: 2.5.1+cu121
Torch CUDA build: 12.1
CUDA available: True
Devices: 1


In [27]:
import torch
print(torch.version.cuda)          
print(torch.cuda.is_available())   
print(torch.cuda.get_device_name(0))


12.1
True
NVIDIA GeForce GTX 1660 SUPER


### Simulating customer data

In [28]:
customer_data = torch.rand(1000000,3,device=device)
customer_data.shape

torch.Size([1000000, 3])

In [29]:
customer_data[:5]

tensor([[0.7365, 0.2522, 0.2269],
        [0.5085, 0.1206, 0.7774],
        [0.1780, 0.2730, 0.2588],
        [0.3782, 0.3896, 0.1423],
        [0.5663, 0.5570, 0.7429]], device='cuda:0')

In [30]:
customer_data[:, 1][:5]

tensor([0.2522, 0.1206, 0.2730, 0.3896, 0.5570], device='cuda:0')

In [31]:
high_spenders = customer_data[customer_data[:, 1] > 0.5]
high_spenders

tensor([[0.5663, 0.5570, 0.7429],
        [0.6784, 0.5509, 0.5008],
        [0.4705, 0.9576, 0.5117],
        ...,
        [0.2973, 0.7686, 0.8246],
        [0.4918, 0.7056, 0.5075],
        [0.5945, 0.9915, 0.8279]], device='cuda:0')

In [32]:
high_spenders.shape

torch.Size([500739, 3])

In [38]:
units = torch.tensor([
    [200,220],
    [150,180],
    [300,330]
],device='cuda')

In [34]:
units.shape

torch.Size([3, 2])

In [35]:
units.dtype

torch.int64

In [39]:
units.device

device(type='cuda', index=0)

In [40]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330], device='cuda:0')

In [42]:
units.view(2,3)

tensor([[200, 220, 150],
        [180, 300, 330]], device='cuda:0')

In [43]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]], device='cuda:0')

In [45]:
units[2,1] = 389
units

tensor([[200, 220],
        [150, 180],
        [300, 389]], device='cuda:0')

In [46]:
torch.rand(3,4)


tensor([[0.4324, 0.7884, 0.2197, 0.3359],
        [0.1163, 0.7633, 0.8665, 0.9456],
        [0.5059, 0.3430, 0.6879, 0.5953]])