

---



Imports and CUDA

In [1]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Using device: cuda




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [2]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]


In [3]:
inventory_t = torch.tensor(inventory, requires_grad=True, dtype=torch.float16)
inventory_t

tensor([[12., 15., 10.,  0.,  5.],
        [10.,  8.,  7.,  5.,  4.],
        [20., 10., 15.,  5.,  2.]], dtype=torch.float16, requires_grad=True)

In [4]:
#2 Find the total inventory for each item across all days
inventory_t.sum(dim=0)

tensor([42., 33., 32., 10., 11.], dtype=torch.float16, grad_fn=<SumBackward1>)

In [5]:
#3 Find the average inventory per day
inventory_t.mean(dim=1)

tensor([ 8.3984,  6.8008, 10.3984], dtype=torch.float16,
       grad_fn=<MeanBackward1>)



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [6]:
#1 Simulate this data using PyTorch's Random Functions
vehicles1 = torch.randint(20,200, (24,))
vehicles2 = torch.randint(20,200, (24,))
vehicles1,vehicles2

(tensor([149, 187,  41, 151, 191,  23, 114, 103,  71,  24, 133,  90, 172,  28,
          89, 153, 131, 143, 193, 159,  28, 113, 109, 134]),
 tensor([137,  64, 145, 100, 104, 153, 113, 157, 155, 174, 196, 199,  63, 133,
          37, 194,  29, 130,  40, 138, 178, 177,  41, 195]))

In [7]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
def calc_single_road(v):
    return v.sum()

road1 = calc_single_road(vehicles1)
road2 = calc_single_road(vehicles2)
road1,road2

(tensor(2729), tensor(3052))

In [8]:

def calc_vehicles(v1, v2):
    return v1.sum() + v2.sum()

all_day = calc_vehicles(vehicles1,vehicles2)
print(all_day)

#3 Write the function to calculate the total vehicle flow for each hour across both roads
vehicles1 + vehicles2

tensor(5781)


tensor([286, 251, 186, 251, 295, 176, 227, 260, 226, 198, 329, 289, 235, 161,
        126, 347, 160, 273, 233, 297, 206, 290, 150, 329])



---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [9]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]
matrix = torch.tensor([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
weight_factor = torch.tensor([0.8,1.2,1.5])
scores = matrix * weight_factor
print(scores)

tensor([[  8.0000,  24.0000,  45.0000],
        [ 32.0000,  60.0000,  90.0000],
        [ 56.0000,  96.0000, 135.0000]])


In [10]:
#2 Find the row-wise and column-wise maximum scores
print(f"max scores row-wise: {scores.max(dim=1)}")
print(f"max scores column-wise: {scores.max(dim=0)}")

max scores row-wise: torch.return_types.max(
values=tensor([ 45.,  90., 135.]),
indices=tensor([2, 2, 2]))
max scores column-wise: torch.return_types.max(
values=tensor([ 56.,  96., 135.]),
indices=tensor([2, 2, 2]))


In [11]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
matrix.view(-1).shape

torch.Size([9])

In [12]:
m_t = matrix.t()
m_t

tensor([[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [21]:
#1 Use PyTorch to compute 'y' for x = 4
x = torch.tensor(4, requires_grad=True, dtype=torch.float16)
y = 2*x**3 + 5* x**2 - 3*x +7

In [22]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd
y.backward()
x.grad

tensor(133., dtype=torch.float16)



---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [23]:
camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])

In [24]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)
camera1 * camera2

tensor([[ 5, 12],
        [21, 32]])

In [25]:
#2 Compute Dot Product of the two matrices
camera1 @ camera2

tensor([[19, 22],
        [43, 50]])

In [26]:
#3 Compute the Determinant of each matrix
det_c1 = torch.det(camera1.float())
det_c2 = torch.det(camera2.float())
print(det_c1,det_c2)

tensor(-2.) tensor(-2.0000)




---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [27]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]
w = torch.tensor(2, requires_grad=True, dtype=torch.float16)
b = torch.tensor(1, requires_grad=True, dtype=torch.float16)
x = torch.tensor([1,2,3,4], requires_grad=True, dtype=torch.float16)

In [28]:
#2 Compute tensors for y
y = w*x +b
print(y)

tensor([3., 5., 7., 9.], dtype=torch.float16, grad_fn=<AddBackward0>)


In [29]:
r = y.sum()
r.backward()
w.grad

tensor(10., dtype=torch.float16)



---

