In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.6510, 0.4967, 0.1828],
        [0.8066, 0.5066, 0.0324],
        [0.3653, 0.8238, 0.3998],
        [0.9919, 0.1757, 0.1885],
        [0.1686, 0.8625, 0.9615]])


In [2]:
#tensor creation

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
t3 = torch.zeros(2,3)#shape 2,3
t4 = torch.rand(2,2)
t5 = torch.arange(0,10,3)
t6 = torch.ones(3,2)
t3,t6

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]))

In [3]:
print(t2.shape)
print(t2.dtype)
print(t2.ndim)
print(t2.device)

torch.Size([2, 2])
torch.float32
2
cpu


In [4]:
print(t3.ndim, t6.ndim)

2 2


In [5]:
a = torch.tensor([1.0,2.0,3.0])
b = torch.tensor([3.0,2.0,1.0])

print(a+b)
print(a*b)
print(torch.dot(a,b)) #scalar
print(a @ b) #scalar

tensor([4., 4., 4.])
tensor([3., 4., 3.])
tensor(10.)
tensor(10.)


In [6]:
torch.mean(a), torch.mean(b)

(tensor(2.), tensor(2.))

In [7]:
a.sum(), a.max(), a.min()

(tensor(6.), tensor(3.), tensor(1.))

In [8]:
a**2, torch.sqrt(a)

(tensor([1., 4., 9.]), tensor([1.0000, 1.4142, 1.7321]))

In [9]:
x = torch.arange(12)
print(x.shape)
x = x.reshape(3,4)
print(x)

torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


### excersises

In [19]:
a_7 = torch.tensor([[7,7,7],[7,7,7],[7,7,7]])
a_by_5 = torch.arange(5,26,5)
tens = torch.rand((4,4))
print(tens.shape)
print(tens.dtype)
tens_64 = tens.type(torch.int64)
print(tens_64.dtype)
tens_64.device
print(torch.full((3,3),7))
print(tens.to(torch.int64))

torch.Size([4, 4])
torch.float32
torch.int64
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
