In [1]:
import numpy as np
import pandas as pd


In [2]:
np.random.seed(42)
data_with_missing = {
    "Main Port Name": np.random.choice(
        ["Port A", "Port B", "Port C", "Port D", None], 50
    ),
    "Country Code": np.random.choice(
        ["United States", "United Kingdom", "France", "Germany", None], 50
    ),
    "Channel Depth (m)": np.random.choice([5, 15, 25, None], 50),
    "Harbor Size": np.random.choice(["Small", "Medium", "Large", None], 50),
    "Anchorage Depth (m)": np.random.choice([10, 20, None], 50),
    "Date": pd.date_range(start="2020-01-01", periods=50, freq="D"),
}

df_with_missing = pd.DataFrame(data_with_missing)

In [3]:
df_with_missing.head(2)

Main Port Name Country Code Channel Depth (m) Harbor Size  \
0         Port D      Germany              None       Small   
1           None      Germany                25       Large   

  Anchorage Depth (m)       Date  
0                None 2020-01-01  
1                  10 2020-01-02

In [8]:
# Policz liczbę brakujących wartości w każdej kolumnie.
# Znajdź procent brakujących danych w każdej kolumnie.
missing_values = df_with_missing.isna().sum()
#missing_values
all_values = len(df_with_missing)
pct_missing = (missing_values / all_values) * 100.0
pct_missing

Main Port Name         20.0
Country Code           18.0
Channel Depth (m)      24.0
Harbor Size            24.0
Anchorage Depth (m)    30.0
Date                    0.0
dtype: float64

In [20]:
# Usuń wiersze, które mają brakujące wartości w kolumnie Channel Depth (m).
# Usuń kolumny, które mają więcej niż 30% brakujących danych.
df_with_missing = df_with_missing.dropna(subset=["Channel Depth (m)"])
df_with_missing.head(3)

#saving dataset without chosen columns
keep_columns = pct_missing[pct_missing < 30].index
df_cleaned = df_with_missing[keep_columns]
df_cleaned.head(3)

Main Port Name   Country Code Channel Depth (m) Harbor Size       Date
1           None        Germany                25       Large 2020-01-02
2         Port C        Germany                 5       Large 2020-01-03
5         Port B  United States                15       Large 2020-01-06

In [19]:
#dropping columns if condition met
to_drop = pct_missing[pct_missing >= 30].index
df_after_dropping = df_with_missing.drop(columns=to_drop)
df_after_dropping.head(3)

Main Port Name   Country Code Channel Depth (m) Harbor Size       Date
1           None        Germany                25       Large 2020-01-02
2         Port C        Germany                 5       Large 2020-01-03
5         Port B  United States                15       Large 2020-01-06

In [22]:
# Uzupełnij braki w kolumnie Channel Depth (m) średnią wartością tej kolumny.



avg_ch = df_with_missing["Channel Depth (m)"].mean()
df_with_missing["Channel Depth (m)"].fillna(avg_ch)
df_with_missing.head(1)


C:\Users\USER\AppData\Local\Temp\ipykernel_19044\6460757.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_with_missing["Channel Depth (m)"].fillna(avg_ch)


Main Port Name Country Code Channel Depth (m) Harbor Size  \
1           None      Germany                25       Large   

  Anchorage Depth (m)       Date  
1                  10 2020-01-02

In [32]:
# W kolumnie Harbor Size:
# Uzupełnij braki wartością "Unknown".
df_with_missing["Harbor Size"] =  df_with_missing["Harbor Size"].fillna("Unknown")


In [36]:
# W kolumnie Anchorage Depth (m) (jeśli istnieje):
# Uzupełnij brakujące wartości medianą dla każdego kraju (Country Code).
median_anch = df_with_missing.groupby("Country Code")["Anchorage Depth (m)"].median()
global_median = df_with_missing["Anchorage Depth (m)"].median()

df_with_missing["Anchorage Depth (m)"] = df_with_missing.apply(
    lambda row: median_anch[row["Country Code"]]
    if pd.notnull(row["Country Code"]) and pd.notnull(median_anch[row["Country Code"]])
    else (global_median if pd.isnull(row["Anchorage Depth (m)"]) else row["Anchorage Depth (m)"]), axis=1
)

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)


In [37]:
df_with_missing

Main Port Name    Country Code Channel Depth (m) Harbor Size  \
1            None         Germany                25       Large   
2          Port C         Germany                 5       Large   
5          Port B   United States                15       Large   
6          Port C         Germany                 5       Small   
8          Port C         Germany                25       Small   
9            None  United Kingdom                25     Unknown   
10         Port D  United Kingdom                15       Large   
12           None            None                 5       Large   
13         Port B  United Kingdom                25      Medium   
16         Port D  United Kingdom                15      Medium   
17           None  United Kingdom                25       Small   
18         Port A         Germany                25      Medium   
19         Port D         Germany                 5       Small   
20         Port B   United States                25       Small   
21           None            None                 5      Medium   
22         Port D            None                25     Unknown   
23         Port A  United Kingdom                15     Unknown   
24         Port A            None                25     Unknown   
25         Port C  United Kingdom                 5     Unknown   
26         Port C   United States                 5     Unknown   
27         Port B         Germany                15      Medium   
28         Port D         Germany                25      Medium   
29         Port D         Germany                25       Large   
30         Port C            None                15     Unknown   
31         Port D   United States                25      Medium   
32         Port D            None                25       Large   
33         Port A            None                 5     Unknown   
34         Port C   United States                25       Small   
35           None   United States                25       Large   
36         Port C   United States                15      Medium   
37           None   United States                15       Small   
39         Port B          France                 5       Small   
40         Port D          France                25       Large   
41         Port A   United States                25      Medium   
43         Port B          France                25     Unknown   
44         Port B   United States                 5       Small   
46         Port B            None                 5       Large   
49         Port D   United States                15     Unknown   

    Anchorage Depth (m)       Date  
1                  15.0 2020-01-02  
2                  15.0 2020-01-03  
5                  20.0 2020-01-06  
6                  15.0 2020-01-07  
8                  15.0 2020-01-09  
9                  20.0 2020-01-10  
10                 20.0 2020-01-11  
12                 20.0 2020-01-13  
13                 20.0 2020-01-14  
16                 20.0 2020-01-17  
17                 20.0 2020-01-18  
18                 15.0 2020-01-19  
19                 15.0 2020-01-20  
20                 20.0 2020-01-21  
21                 10.0 2020-01-22  
22                 10.0 2020-01-23  
23                 20.0 2020-01-24  
24                 10.0 2020-01-25  
25                 20.0 2020-01-26  
26                 20.0 2020-01-27  
27                 15.0 2020-01-28  
28                 15.0 2020-01-29  
29                 15.0 2020-01-30  
30                 10.0 2020-01-31  
31                 20.0 2020-02-01  
32                 20.0 2020-02-02  
33                 20.0 2020-02-03  
34                 20.0 2020-02-04  
35                 20.0 2020-02-05  
36                 20.0 2020-02-06  
37                 20.0 2020-02-07  
39                 20.0 2020-02-09  
40                 20.0 2020-02-10  
41                 20.0 2020-02-11  
43                 20.0 2020-02-13  
44                 20.0 2020-02-14  
46                 2

In [39]:
#Utwórz tablicę numpy z listy [10, 20, 30, 40].
l = [10,20,30,40]
t = np.array(l)
type(t)


numpy.ndarray

In [49]:
#Utwórz tablicę 2D (2x3) z wartościami od 1 do 6.
t2 = np.arange(6).reshape((2,3))
t2

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
#Dodaj liczbę 5 do każdej wartości w pierwszej tablicy.
t = t+5
print(t)

t = t*2
print(t)

[20 30 40 50]
[ 40  60  80 100]


In [45]:
t= t.astype(float)
t

array([ 40.,  60.,  80., 100.])

In [46]:
#Wyświetl kształt (shape) i liczbę wymiarów (ndim) dla obu tablic
print(t.shape)
print(t.ndim)

(4,)
1


In [48]:
print(t[0])
print(t[1])
print(t[1:3])

40.0
60.0
[60. 80.]


In [55]:
t2

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
print(t2[0], t2[:, 1])

[0 1 2] [1 4]


In [59]:
print(t2[0])
print(t2[:, 1])

[0 1 2]
[1 4]


In [62]:
# W tablicy t wybierz elementy większe niż 50.
# W tablicy t2 wybierz wszystkie wartości, które są większe niż 3.
liczby = t > 50
print(t[liczby])
more_than_3 = t2 > 3
print(t2[more_than_3])

[ 60.  80. 100.]
[4 5]


In [64]:
# Zmień wszystkie elementy tablicy t, które są większe niż 50, na wartość 99.
# Zmień wszystkie wartości w tablicy t2, które są większe niż 3, na 0.
t[liczby] = 99
print(t)

t2[more_than_3] = 0
print(t2)


[40. 99. 99. 99.]
[[0 1 2]
 [3 0 0]]


In [66]:
# zmień tablicę t (1D) na tablicę 2D o wymiarach (4, 1).


t = t.reshape(4,1)
print(t.shape)

# Dodaj nowy wymiar do tablicy t2, aby miała kształt (2, 3, 1).
t2 = t2.reshape((2,3,1))
print(t2.shape)


(4, 1)
(2, 3, 1)
