In [3]:
import sympy as sp

# Definiujemy zmienną x i funkcję f(x)
x = sp.Symbol('x')
f = x**3 + 2*x**2 - 5*x + 7

# Obliczamy pochodną
f_prime = sp.diff(f, x)
print("Pochodna f(x):", f_prime)


Pochodna f(x): 3*x**2 + 4*x - 5


In [4]:
# Obliczamy pochodną w x=2
f_prime_value = f_prime.subs(x, 2)
print("Pochodna w x=2:", f_prime_value)


Pochodna w x=2: 15


In [5]:
# Definiujemy zmienne x, y i funkcję g(x, y)
y = sp.Symbol('y')
g = x**2 + 3*x*y + y**2

# Pochodne cząstkowe
g_dx = sp.diff(g, x)  # Pochodna po x
g_dy = sp.diff(g, y)  # Pochodna po y

print("Pochodna po x:", g_dx)
print("Pochodna po y:", g_dy)


Pochodna po x: 2*x + 3*y
Pochodna po y: 3*x + 2*y


In [6]:
# Gradient funkcji g(x, y)
gradient = sp.Matrix([g_dx, g_dy])
print("Gradient:\n", gradient)


Gradient:
 Matrix([[2*x + 3*y], [3*x + 2*y]])


In [7]:
import numpy as np

# Funkcja kosztu J(w) = w^2 + 3w + 2
def cost_function(w):
    return w**2 + 3*w + 2

# Pochodna funkcji kosztu
def cost_derivative(w):
    return 2*w + 3

# Gradient Descent
def gradient_descent(learning_rate=0.1, epochs=10):
    w = np.random.randn()  # Inicjalizacja losowego w
    for i in range(epochs):
        grad = cost_derivative(w)
        w -= learning_rate * grad  # Aktualizacja wag
        print(f"Iteracja {i+1}: w = {w:.4f}, J(w) = {cost_function(w):.4f}")

gradient_descent()


Iteracja 1: w = 1.2062, J(w) = 7.0735
Iteracja 2: w = 0.6650, J(w) = 4.4371
Iteracja 3: w = 0.2320, J(w) = 2.7497
Iteracja 4: w = -0.1144, J(w) = 1.6698
Iteracja 5: w = -0.3915, J(w) = 0.9787
Iteracja 6: w = -0.6132, J(w) = 0.5364
Iteracja 7: w = -0.7906, J(w) = 0.2533
Iteracja 8: w = -0.9325, J(w) = 0.0721
Iteracja 9: w = -1.0460, J(w) = -0.0439
Iteracja 10: w = -1.1368, J(w) = -0.1181


In [8]:
from scipy.sparse import csr_matrix

# Tworzenie macierzy rzadkiej
A_sparse = csr_matrix([[1, 0, 0], [0, 0, 2], [0, 3, 0]])

# Konwersja do pełnej macierzy
A_dense = A_sparse.toarray()


In [9]:
from sklearn.linear_model import LinearRegression

# Dane wejściowe
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2.2, 2.8, 3.6, 4.5, 5.1])

# Model regresji
model = LinearRegression()
model.fit(X, y)

# Predykcja
y_pred = model.predict(X)


In [10]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
cross_product = np.cross(v1, v2)


In [11]:
proj_v1_on_v2 = (np.dot(v1, v2) / np.dot(v2, v2)) * v2


In [1]:
import numpy as np

# Tworzenie macierzy ortogonalnej
Q, R = np.linalg.qr(np.random.rand(3, 3))  # QR decomposition

# Sprawdzenie czy Q jest ortogonalna (Q^T * Q ≈ I)
identity_check = np.allclose(Q.T @ Q, np.eye(3))
print("Czy Q jest ortogonalna?", identity_check)


Czy Q jest ortogonalna? True


In [2]:
# Wektory bazowe standardowej przestrzeni 3D
basis_vectors = np.eye(3)
print("Baza standardowa przestrzeni 3D:")
print(basis_vectors)


Baza standardowa przestrzeni 3D:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank_A = np.linalg.matrix_rank(A)
print("Rząd macierzy:", rank_A)  # Dla tej macierzy wynik to 2, bo wiersze są liniowo zależne


Rząd macierzy: 2


In [4]:
# Macierz transformacji
T = np.array([[2, 0], [0, 3]])

# Wektor do przekształcenia
v = np.array([1, 2])

# Zastosowanie transformacji
v_transformed = T @ v
print("Wektor po transformacji:", v_transformed)


Wektor po transformacji: [2 6]


In [5]:
theta = np.pi / 4  # 45 stopni
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
v_rotated = R @ v
print("Wektor po obrocie:", v_rotated)


Wektor po obrocie: [-0.70710678  2.12132034]


In [6]:
def gram_schmidt(V):
    U = np.zeros_like(V, dtype=np.float64)
    for i in range(V.shape[1]):
        U[:, i] = V[:, i]
        for j in range(i):
            U[:, i] -= np.dot(U[:, j], V[:, i]) / np.dot(U[:, j], U[:, j]) * U[:, j]
        U[:, i] /= np.linalg.norm(U[:, i])
    return U

# Macierz wektorów
V = np.array([[1, 1], [1, -1]], dtype=np.float64)
U = gram_schmidt(V)
print("Ortogonalne wektory:\n", U)


Ortogonalne wektory:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [7]:
v = np.array([3, 4])
u = np.array([1, 1])

# Rzut wektora v na u
proj_v_on_u = (np.dot(v, u) / np.dot(u, u)) * u
print("Rzut wektora:", proj_v_on_u)


Rzut wektora: [3.5 3.5]


In [8]:
from scipy.linalg import lu

A = np.array([[4, 3], [6, 3]])
P, L, U = lu(A)

print("Macierz dolna (L):\n", L)
print("Macierz górna (U):\n", U)


Macierz dolna (L):
 [[1.         0.        ]
 [0.66666667 1.        ]]
Macierz górna (U):
 [[6. 3.]
 [0. 1.]]


In [9]:
A = np.array([[2, 1], [1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Wartości własne:", eigenvalues)
print("Wektory własne:\n", eigenvectors)


Wartości własne: [3. 1.]
Wektory własne:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [10]:
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, Vt = np.linalg.svd(A)

print("Macierz U:\n", U)
print("Wartości osobliwe S:\n", S)
print("Macierz V^T:\n", Vt)


Macierz U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Wartości osobliwe S:
 [9.52551809 0.51430058]
Macierz V^T:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [11]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A_pinv = np.linalg.pinv(A)
print("Macierz pseudoodwrotna:\n", A_pinv)


Macierz pseudoodwrotna:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [12]:
A = np.array([[4, 2], [2, 3]])
L = np.linalg.cholesky(A)
print("Macierz Choleskiego:\n", L)


Macierz Choleskiego:
 [[2.         0.        ]
 [1.         1.41421356]]


In [13]:
def power_iteration(A, num_simulations=100):
    b_k = np.random.rand(A.shape[1])
    
    for _ in range(num_simulations):
        b_k1 = np.dot(A, b_k)
        b_k = b_k1 / np.linalg.norm(b_k1)
    
    eigenvalue = np.dot(b_k.T, np.dot(A, b_k))
    return eigenvalue, b_k

A = np.array([[4, 1], [1, 3]])
eigenvalue, eigenvector = power_iteration(A)
print("Największa wartość własna:", eigenvalue)
print("Wektor własny:", eigenvector)


Największa wartość własna: 4.618033988749896
Wektor własny: [0.85065081 0.52573111]
