In [1]:
import pandas as pd
import numpy as np

In [2]:
data1 = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Country": ["USA", "UK", "France", "Germany", "Canada"]
}
df1 = pd.DataFrame(data1)
data2 = {
    "ID": [3, 4, 5, 6, 7],
    "Sales": [200, 150, 300, 400, 500],
    "Year": [2021, 2022, 2021, 2022, 2023]
}
df2 = pd.DataFrame(data2)

In [4]:
df = df1.merge(df2, on="ID", how="inner")
df

ID     Name  Country  Sales  Year
0   3  Charlie   France    200  2021
1   4    David  Germany    150  2022
2   5      Eve   Canada    300  2021

In [5]:
df_left = df1.merge(df2, on="ID", how='left')
df_left

ID     Name  Country  Sales    Year
0   1    Alice      USA    NaN     NaN
1   2      Bob       UK    NaN     NaN
2   3  Charlie   France  200.0  2021.0
3   4    David  Germany  150.0  2022.0
4   5      Eve   Canada  300.0  2021.0

In [6]:
df_outer = df1.merge(df2, how="outer", on="ID")
df_outer

ID     Name  Country  Sales    Year
0   1    Alice      USA    NaN     NaN
1   2      Bob       UK    NaN     NaN
2   3  Charlie   France  200.0  2021.0
3   4    David  Germany  150.0  2022.0
4   5      Eve   Canada  300.0  2021.0
5   6      NaN      NaN  400.0  2022.0
6   7      NaN      NaN  500.0  2023.0

In [16]:
data1 = {"ID" : [1,2,3], "Name": ["L", "Z", "G"], "Country": ["PL", "GR", "SI"]}
data2 = {"ID" : [1,2,3], "Sales": [10,20,30], "Year": [1990,1991,1992]}
df1 = pd.DataFrame(data1).set_index("ID")
df2 = pd.DataFrame(data2).set_index("ID")

In [17]:
df = df1.join(df2)
df

Name Country  Sales  Year
ID                          
1     L      PL     10  1990
2     Z      GR     20  1991
3     G      SI     30  1992

In [18]:
# Dataset do Zadania 3 (Q1 i Q2)
data_q1 = {
    "ID": [1, 2, 3],
    "Sales": [100, 150, 200],
    "Quarter": ["Q1", "Q1", "Q1"]
}
data_q2 = {
    "ID": [4, 5, 6],
    "Sales": [250, 300, 350],
    "Quarter": ["Q2", "Q2", "Q2"]
}
df_q1 = pd.DataFrame(data_q1)
df_q2 = pd.DataFrame(data_q2)

In [22]:
df_0 = pd.concat((df_q1, df_q2), axis=0)
df_0

ID  Sales Quarter
0   1    100      Q1
1   2    150      Q1
2   3    200      Q1
0   4    250      Q2
1   5    300      Q2
2   6    350      Q2

In [23]:
df_1 = pd.concat((df_q1, df_q2), axis=1)
df_0

ID  Sales Quarter
0   1    100      Q1
1   2    150      Q1
2   3    200      Q1
0   4    250      Q2
1   5    300      Q2
2   6    350      Q2

In [32]:
# Dataset do Zadania 4 (duplikaty)
data_dup1 = {
    "ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Country": ["USA", "UK", "France", "Germany"]
}
data_dup2 = {
    "ID": [3, 4, 5, 6],
    "Name": ["Charlie", "David", "Eve", "Frank"],
    "Country": ["France", "Germany", "Canada", "Italy"]
}
df_dup1 = pd.DataFrame(data_dup1)
df_dup2 = pd.DataFrame(data_dup2)

In [33]:
df = df_dup1.merge(df_dup2, on="ID", how="left")
df = df.drop_duplicates(keep="first")
df

ID   Name_x Country_x   Name_y Country_y
0   1    Alice       USA      NaN       NaN
1   2      Bob        UK      NaN       NaN
2   3  Charlie    France  Charlie    France
3   4    David   Germany    David   Germany

In [42]:
t = np.random.randint(10, size=(2,4))
print(f"srednia: {np.mean(t)}\nmediana: {np.median(t)}\nstd: {round(np.std(t),2)}")
print(f"{np.max(t)}, {np.min(t)}")

srednia: 5.5
mediana: 4.5
std: 2.4
9, 2


In [48]:
t2 = np.random.randint(20, size=(3,6))
print(t2)
np.sum(t2, axis=1) #kolumny
np.sum(t2, axis=0) #wiersze
np.mean(t2, axis=1) #sr kolumny

[[12 11  0  6  0  6]
 [15  5 19 16 12 18]
 [11 18 17 15 14 15]]


array([ 5.83333333, 14.16666667, 15.        ])

In [49]:
for x in np.mean(t2, axis=1):
    print(x)

5.833333333333333
14.166666666666666
15.0


In [53]:
t = np.random.randint(100, size=(3,10))
mask = t > 40
np.mean(t[mask])

67.73913043478261

In [62]:
arr = np.random.rand(10,10)
max_index = np.unravel_index(np.argmax(arr), arr.shape)
arr[max_index]

0.9959402420463809