In [1]:
import numpy as np

In [2]:



vector_row = np.array([1, 2, 3])
print("Wektor wierszowy:", vector_row)


vector_column = np.array([[1], [2], [3]])
print("Wektor kolumnowy:\n", vector_column)


Wektor wierszowy: [1 2 3]
Wektor kolumnowy:
 [[1]
 [2]
 [3]]


In [3]:

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Macierz:\n", matrix)


Macierz:
 [[1 2 3]
 [4 5 6]]


In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Dodawanie macierzy
C = A + B
print("Suma macierzy:\n", C)

# Odejmowanie macierzy
D = A - B
print("Różnica macierzy:\n", D)


Suma macierzy:
 [[ 6  8]
 [10 12]]
Różnica macierzy:
 [[-4 -4]
 [-4 -4]]


In [5]:
# Mnożenie element po elemencie
E = A * B
print("Mnożenie element po elemencie:\n", E)

# Iloczyn macierzy (mnożenie macierzowe)
F = A @ B
print("Iloczyn macierzy:\n", F)

# Alternatywnie
G = np.dot(A, B)
print("Iloczyn macierzy (dot):\n", G)


Mnożenie element po elemencie:
 [[ 5 12]
 [21 32]]
Iloczyn macierzy:
 [[19 22]
 [43 50]]
Iloczyn macierzy (dot):
 [[19 22]
 [43 50]]


In [6]:
print("Macierz przed transpozycją:\n", A)
print("Macierz po transpozycji:\n", A.T)



Macierz przed transpozycją:
 [[1 2]
 [3 4]]
Macierz po transpozycji:
 [[1 3]
 [2 4]]


In [7]:
from numpy.linalg import det

det_A = det(A)
print("Determinant macierzy A:", det_A)


Determinant macierzy A: -2.0000000000000004


In [8]:
from numpy.linalg import inv

if det_A != 0:
    inv_A = inv(A)
    print("Macierz odwrotna A:\n", inv_A)
else:
    print("Macierz nie jest odwracalna")


Macierz odwrotna A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
from numpy.linalg import solve

A = np.array([[2, 3], [5, 7]])
B = np.array([8, 19])

X = solve(A, B)
print("Rozwiązanie układu równań:", X)


Rozwiązanie układu równań: [1. 2.]


In [10]:
# Dane wejściowe (X) i wartości (Y)
X = np.array([[1, 1], [1, 2], [1, 3]])
Y = np.array([2, 2.5, 3.5])

# Obliczanie wag W
W = np.linalg.inv(X.T @ X) @ X.T @ Y
print("Wagi regresji liniowej:", W)


Wagi regresji liniowej: [1.16666667 0.75      ]


In [11]:
# Gradient Descent dla regresji liniowej
def gradient_descent(X, Y, learning_rate=0.01, epochs=1000):
    m, n = X.shape
    W = np.zeros(n)  # Inicjalizacja wag
    for i in range(epochs):
        gradient = -(2/m) * X.T @ (Y - X @ W)
        W -= learning_rate * gradient
    return W

W_gd = gradient_descent(X, Y)
print("Wagi po Gradient Descent:", W_gd)


Wagi po Gradient Descent: [1.10349936 0.77778741]
